#pragma once

#include <Arduino.h>

#define ENABLE_DEBUG

#define INPUT_SWITCH_IN_MENU

#define SHORT_CLICK_DUR_MS 70
#define LONG_CLICK_DUR_MS 500
#define ENABLE_PUSH_LENGTH_INDICATOR
#define SHORT_PUSH_INDICATOR_LENGTH 8
#define LONG_PUSH_INDICATOR_LENGTH 16

#define BACK_TO_MAIN_SCREEN_TIMEOUT_S 120
#define BACK_TO_MAIN_SCREEN_POPUP_TIMEOUT_S 5

#define ENABLE_SCREEN_SAVER
#define SCREEN_SAVER_TIMEOUT_S 300

#define UPDATE_TEMP_INTERVAL_MS 2000

#define POTENTIOMETER_PULLING_RATE_MS 50
#define POTENTIOMETER_MIN_CHANGE 150

#define SETTING_SAVE_INTERVAL_MS 5000

#define ENABLE_SPECTRUM_ANALYZER
#ifdef ENABLE_SPECTRUM_ANALYZER
#define SPECTRUM_IN_MENU
#define SPECTRUM_AS_SCREEN_SAVER
#endif
#define SPECTRUM_AVG_BUFFER 8 // 2, 4, 8, 16, 32, 64 ...
#define SPECTRUM_DIVISOR 3
#define SPECTRUM_MAX_VAL 4095
#define SPECTRUM_UPDATE_INTERVAL_MS 10
